express= require('express')
app = express()
cp= require('cookie-parser')
app.use(cp())
app.get('/cookie', function(req,res){
    res.cookie('name','express JS')
    res.cookie('fname','Prithvi')
    res.cookie('lname','Patel')
    res.cookie('ID','2',{expires:new Date(Date.now()+10000)})
    res.cookie('email','p@gmail.com',{maxAge:5000})
    res.clearCookie('lname')
    res.send(req.cookies)
})
app.listen(3010)